language: ruby
cache: bundler
sudo: required
dist: trusty
before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
rvm:
  - 2.2.2
  - 2.3.0
env:
  - CAPYBARA_DRIVER=headless_chrome
after_success:
  - coveralls
notifications:
  email: false
