language: ruby
sudo: false
cache: bundler
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
rvm:
  - 2.2.2
  - 2.3.0
env:
  - CAPYBARA_DRIVER=headless_chrome
after_success:
  - coveralls
notifications:
  email: false
